// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "PostExpression.hpp"
TEST_CASE("Ex1 ", "[example]")
{
	string postfix1 = "243*+5+";
	PostExpression p1(postfix1);
	int expected = 2 + 4 * 3 + 5;
	int result = p1.evaluate();
	cout << "Expected: " << expected << endl;
	cout << "Result: " << result << endl;
	REQUIRE(p1.evaluate() == expected);

}

TEST_CASE("Ex2 ", "[example]")
{
	string postfix2 = "34562*+*+9+";
	PostExpression p2(postfix2);
	int expected = 3 + (4 * (5 + (6 * 2))) + 9;
	int result = p2.evaluate();
	cout << "Expected: " << expected << endl;
	cout << "Result: " << result << endl;
	REQUIRE(p2.evaluate() == expected);
}

TEST_CASE("Ex3 ", "[example]")
{
	string postfix3 = "345*+23*+95-2*+";
	PostExpression p3(postfix3);
	int expected = (3+4*5)+2*3+(9-5)*2;
	int result = p3.evaluate();
	cout << "Expected: " << expected << endl;
	cout << "Result: " << result << endl;
	REQUIRE(p3.evaluate() == expected);
}